package pe.upeu.serva.entity;
// Generated 01/05/2017 02:26:18 PM by Hibernate Tools 4.3.1



/**
 * Ingrediente generated by hbm2java
 */
public class Ingrediente  implements java.io.Serializable {


     private Long id;
     private Producto producto;
     private Receta receta;
     private Double cantidad;
     private Double costo;

    public Ingrediente() {
    }

    public Ingrediente(Producto producto, Receta receta, Double cantidad, Double costo) {
       this.producto = producto;
       this.receta = receta;
       this.cantidad = cantidad;
       this.costo = costo;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Receta getReceta() {
        return this.receta;
    }
    
    public void setReceta(Receta receta) {
        this.receta = receta;
    }
    public Double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Double cantidad) {
        this.cantidad = cantidad;
    }
    public Double getCosto() {
        return this.costo;
    }
    
    public void setCosto(Double costo) {
        this.costo = costo;
    }




}


