package pe.upeu.serva.entity;
// Generated 01/05/2017 02:26:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu  implements java.io.Serializable {


     private Long id;
     private String tipoMenu;
     private Double costo;
     private Date fecha;
     private Set recetamenus = new HashSet(0);

    public Menu() {
    }

    public Menu(String tipoMenu, Double costo, Date fecha, Set recetamenus) {
       this.tipoMenu = tipoMenu;
       this.costo = costo;
       this.fecha = fecha;
       this.recetamenus = recetamenus;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getTipoMenu() {
        return this.tipoMenu;
    }
    
    public void setTipoMenu(String tipoMenu) {
        this.tipoMenu = tipoMenu;
    }
    public Double getCosto() {
        return this.costo;
    }
    
    public void setCosto(Double costo) {
        this.costo = costo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getRecetamenus() {
        return this.recetamenus;
    }
    
    public void setRecetamenus(Set recetamenus) {
        this.recetamenus = recetamenus;
    }




}


