package pe.upeu.serva.entity;
// Generated 01/05/2017 02:26:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Long id;
     private Categoria categoria;
     private Unidad unidad;
     private String nombre;
     private String descripcion;
     private Double cantidad;
     private Double costo;
     private Set ingredientes = new HashSet(0);

    public Producto() {
    }

    public Producto(Categoria categoria, Unidad unidad, String nombre, String descripcion, Double cantidad, Double costo, Set ingredientes) {
       this.categoria = categoria;
       this.unidad = unidad;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.cantidad = cantidad;
       this.costo = costo;
       this.ingredientes = ingredientes;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Unidad getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(Unidad unidad) {
        this.unidad = unidad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Double cantidad) {
        this.cantidad = cantidad;
    }
    public Double getCosto() {
        return this.costo;
    }
    
    public void setCosto(Double costo) {
        this.costo = costo;
    }
    public Set getIngredientes() {
        return this.ingredientes;
    }
    
    public void setIngredientes(Set ingredientes) {
        this.ingredientes = ingredientes;
    }




}


