package pe.upeu.serva.entity;
// Generated 01/05/2017 02:26:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Receta generated by hbm2java
 */
public class Receta  implements java.io.Serializable {


     private Long id;
     private String nombre;
     private String descripcion;
     private Integer porcion;
     private String preparacion;
     private Double costo;
     private Set recetamenus = new HashSet(0);
     private Set ingredientes = new HashSet(0);

    public Receta() {
    }

    public Receta(String nombre, String descripcion, Integer porcion, String preparacion, Double costo, Set recetamenus, Set ingredientes) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.porcion = porcion;
       this.preparacion = preparacion;
       this.costo = costo;
       this.recetamenus = recetamenus;
       this.ingredientes = ingredientes;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getPorcion() {
        return this.porcion;
    }
    
    public void setPorcion(Integer porcion) {
        this.porcion = porcion;
    }
    public String getPreparacion() {
        return this.preparacion;
    }
    
    public void setPreparacion(String preparacion) {
        this.preparacion = preparacion;
    }
    public Double getCosto() {
        return this.costo;
    }
    
    public void setCosto(Double costo) {
        this.costo = costo;
    }
    public Set getRecetamenus() {
        return this.recetamenus;
    }
    
    public void setRecetamenus(Set recetamenus) {
        this.recetamenus = recetamenus;
    }
    public Set getIngredientes() {
        return this.ingredientes;
    }
    
    public void setIngredientes(Set ingredientes) {
        this.ingredientes = ingredientes;
    }




}


