package pe.upeu.serva.entity;
// Generated 01/05/2017 02:26:18 PM by Hibernate Tools 4.3.1



/**
 * Recetamenu generated by hbm2java
 */
public class Recetamenu  implements java.io.Serializable {


     private Long id;
     private Menu menu;
     private Receta receta;
     private Usuario usuario;
     private Integer porcion;
     private Double costo;

    public Recetamenu() {
    }

    public Recetamenu(Menu menu, Receta receta, Usuario usuario, Integer porcion, Double costo) {
       this.menu = menu;
       this.receta = receta;
       this.usuario = usuario;
       this.porcion = porcion;
       this.costo = costo;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }
    public Receta getReceta() {
        return this.receta;
    }
    
    public void setReceta(Receta receta) {
        this.receta = receta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Integer getPorcion() {
        return this.porcion;
    }
    
    public void setPorcion(Integer porcion) {
        this.porcion = porcion;
    }
    public Double getCosto() {
        return this.costo;
    }
    
    public void setCosto(Double costo) {
        this.costo = costo;
    }




}


