package pe.upeu.serva.entity;
// Generated 01/05/2017 02:26:18 PM by Hibernate Tools 4.3.1



/**
 * Tipomenu generated by hbm2java
 */
public class Tipomenu  implements java.io.Serializable {


     private Long id;
     private String nombre;

    public Tipomenu() {
    }

    public Tipomenu(String nombre) {
       this.nombre = nombre;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


